name: zpevnik

publish_to: 'none'

version: 3.1.6+152

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  proscholy_common:
    path: proscholy-phone-common

  sqflite: ^2.0.2+1
  firebase_core: ^3.10.1
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.1.3
  path: ^1.9.1
  sentry_flutter: ^8.12.0
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcon
      fonts:
        - asset: packages/proscholy_common/assets/fonts/CustomIcon.ttf

    - family: KaiseiHarunoUmi
      fonts:
        - asset: packages/proscholy_common/assets/fonts/KaiseiHarunoUmi-Regular.ttf

    - family: Amiri
      fonts:
        - asset: packages/proscholy_common/assets/fonts/Amiri-Regular.ttf

  assets:
    - assets/data.json
    - assets/images/logos/